---
# Post tasks

- name: Perform YUM package cleanup
  command: yum -y autoremove
  changed_when: no
  ignore_errors: yes
  when:
      - ansible_os_family == 'RedHat'
  tags:
      - skip_ansible_lint
